version: '3' 
name:  "mytodoapi"
services:
  api:
    build:
      context: ./composetodo
      dockerfile: Dockerfile.dev
    depends_on:
      -  postgres_db
    ports:
      - "8000:8000"
    networks:
      - mytodoapi-net
  postgres_db:
    image: postgres:latest
    restart: always
    container_name: postgresCont
    environment:
      - POSTGRES_USER=Lahore_owner
      - POSTGRES_PASSWORD=pxb8XPgYK6hI
      - POSTGRES_DB=Lahore
    ports:
      -  '5433:5432'
        
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - mytodoapi-net
    
  
volumes:
  postgres_db:
    driver: local

networks:
  mytodoapi-net: