import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GenAI-Institute",
  description: "Generated by create next app for GenAI-Instiute",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Header />
      <div className="relative px-6 md:px-20 mr-0 justify-center items-center" style={{ paddingTop: '100px' }}>
  {/* Add padding-top to adjust for fixed header */}
  <video
    autoPlay
    loop
    muted
    className="absolute inset-0 w-full h-full object-cover"
    style={{ zIndex: -1 }} // Ensure the video is behind other content
  >
    <source src="images/AI-Background.mp4" type="video/mp4" />
    Your browser does not support the video tag.
  </video>
  {/* Overlay content */}
  <div className="relative z-10">{children}</div>
</div>


      <Footer />
    </html>
  );
}
