# Use an official Python runtime as a parent image
FROM python:3.12

LABEL maintainer="Mobi"
# Set the working directory in the container
WORKDIR /composetodo
# Install system dependencies required for potential Python packages

# Install Poetry and dependencies
RUN pip install poetry 

# Copy the current directory contents into the container at /code
COPY . /composetodo/
# Configuration to avoid creating virtual environments inside the Docker container

# Install dependencies including development ones

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Run the app. CMD can be overridden when starting the container
CMD ["poetry", "run", "uvicorn", "todoapp.main:app", "--host", "127.0.0.1", "--reload"]